title: Nathaniel Burgdorfer
description: >
  Nathaniel Burgdorfer
  Computer Vision
  Stevens Institute of Technology
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nburgdorfer.github.io"
site-twitter:

# Author Settings
author: Nathaniel Burgdorfer
author-img: headshot.jpg
about-author: Ph.D. Student | Computer Vision | Stevens Institute of Technology
#social-twitter:
#social-facebook:
social-google-scholar: https://scholar.google.com/citations?user=9NjmhkYAAAAJ&hl=en
social-github: nburgdorfer
social-linkedin: nathaniel-Burgdorfer
social-email: nburgdorfer@gmail.com

# Disqus
#discus-identifier: Nathaniel # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
